#!/usr/bin/env bash

# This file is gitignored
# IMPORTANT!! don't check in the real tokens
export SLACK_BDD_API_TOKEN=xoxb-287903457776-1291648388694-frwtkkCxxygmISWPiOwG5Qkx
export ROBBINS_BOT_TOKEN=xoxb-287903457776-778486608183-K3a9jTEeOZkJPnfzJK1VYUXv
export DAVE_BOT_TOKEN=xoxb-287903457776-770225171793-M5fMcw4OGbJqe2uTl2073A1b
export FENDY_BOT_TOKEN=xoxb-287903457776-785260215221-NGl8SKvigqVwsa1IlmCTW7O1
# IMPORTANT!! don't check in the real tokens
